#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
mocap_node:
    ros__parameters:
        rigid_bodies:
            12:
                pose: "whiteMav/pose"
                pose2d: "whiteMav/ground_pose"
                odom: "whiteMav/Odom"
                tf: "tf"
                child_frame_id: "drone_1"
                parent_frame_id: "map"
            8:
                pose: "leader/pose"
                pose2d: "leader/ground_pose"
                odom: "leader/Odom"
                tf: "tf"
                child_frame_id: "drone_2"
                parent_frame_id: "map"
        optitrack_config:
            multicast_address: "239.255.42.99"
            command_port: 1510
            data_port: 9000
            enable_optitrack: true
